version: "3.6"

services:
  redis:
    container_name: urbo_redis_api
    image: redis:latest
    command: redis-server --maxmemory 500mb --maxmemory-policy allkeys-lru
    networks:
      - net_urbo_api
    restart: unless-stopped

  api:
    image: geographica/urbocore_api:production
    container_name: urbo_api
    networks:
      - net_urbo_api
    restart: unless-stopped

networks:
  net_urbo_api:
