version: "3"

services:
  postgis:
    image: geographica/postgis:breezy_badger
    volumes:
      - db-data:/data
      - ./:/usr/src

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  api:
    build: .
    ports:
      - "3005:3000"

volumes:
  db-data:
