site_name: URBO API
pages:
- Home: index.md
- API Reference:
  - Metadata: reference/metadata.md
  - Scopes: reference/scopes.md
  - Entities: reference/entities.md
  - Variables: reference/variables.md
  - Devices: reference/devices.md
  - Maps: reference/maps.md
  - Users: reference/users.md
  - Logs: reference/logs.md
  - Admin:
    - Scopes : reference/admin/scopes.md
  # Verticals docs go here
- Sockets: sockets.md
- Database: database.md
- Filtering:
  - the_geom: geom_filter.md
